brews:
  - tap:
      owner: bricks-cloud
      name: homebrew-bricks
      branch: main

    folder: Formula
    homepage: https://github.com/bricks-cloud/homebrew-bricks


before:
  hooks:
    - go mod vendor
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/bricks/main.go
    goos:
      - linux
      - windows
      - darwin
archives:
    # default format for Mac (darwin) and Linux
  - format: tar.gz
      # if the OS is windows, we override and put everything in a .zip instead.
    format_overrides:
      - goos: windows
        format: zip
      # Just the naming convention for tarballs... Example: msconsole_1.0.0_darwin_64bit
    name_template: '{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}'
      # Replace the cryptic arch's with readable human naming conventions
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
